name: PR Organizer

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  label-and-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add triage label to issues
        if: github.event_name == 'issues'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            triage

      - name: Add triage label to pull requests
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            triage

